### PR TITLE
Update Python bindings

### PR DESCRIPTION
**Pull request by dschwen**
Refs #68

### CODE REVIEW

**Comment by dschwen** [comment]
cool... on my machine `clang-format -i hit.cc` locks up

**Comment by dschwen** [comment]
It takes almost 10min to run `clang-format` on `hit.cpp`, which is an autogenerated 623kB file! IMO it makes no sense to enforce formatting conventions on autogenerated files. Is there a way to add an exclusion list?

**Comment by dschwen** [comment]
To add insult to injury, clang-format 10 (on Civet) and my local clang-format 11 (from the conda environment) format this file differently 👿

**Comment by dschwen** [comment]
DO NOT MERGE. The green is a lie! The python tests are broken!

**Comment by dschwen** [comment]
Ok, I think I've got it now!

**Review by rwcarlsen — APPROVED** [review]

**Pull request merged**
