### PR TITLE
Add merge functionality

### LINKED ISSUE #66: Add `hit merge` command to combine multiple HIT files
A `merge` function will combine multiple HIT files on the AST level, fusing blocks together. E.g.

A file 

```
[Parent]
  [child1]
     param1 = value1
  []
[]
```

and a file

```
[Parent]
  [child1]
     param2 = value2
  []
[]
```

would be fused to

```
[Parent]
  [child1]
     param1 = value1
     param2 = value2
  []
[]
```

### PR DESCRIPTION
**Pull request by dschwen**
This is somewhat of a substitution of the missing `#include` directive. I can have common blocks and parameters in a separate file and can automatically generate complete inputs with this.

Closes #66

### CODE REVIEW

**Comment by dschwen** [comment]
## Not Found
The requested URL /moosetools/docs/PRs/67/style.patch was not found on this server.

**Comment by dschwen** [comment]
@milljm

**Comment by rwcarlsen** [comment]
I think this is fine - but we need to get a proper `.clang-format` file to match the one in the moose repo.

**Comment by milljm** [comment]
@dschwen Fixed.

**Comment by dschwen** [comment]
Ok, I checked in the moose `.clang-format` rules.

**Review by rwcarlsen — APPROVED** [review]

**Pull request merged**
