### PR TITLE
Add `hit diff` functionality

### LINKED ISSUE #94: Add `hit diff` functionality
To compare inputs regardless of order and whitespace and with the ability to compare merged inputs I'm proposing to add a `hit diff` function.

```
hit diff --left input1.i input2.i --right input3.i input4.i input5.i
```

### PR DESCRIPTION
**Pull request by dschwen**
Closes #94

### CODE REVIEW

**Comment by dschwen** [comment]
Example output

image

**Comment by dschwen** [comment]
This strictly diffs on parameters only, meaning an empty block on either side would not show up. In MOOSE-based apps however we have some actions that will get triggered by the mere presence of an empty block (like the `[PerformanceOutputs][]` action). For MOOSE purposes it would probably be useful to compile a list of all section paths as well. Opinions?

**Comment by rwcarlsen** [comment]
Or maybe we could just make moose not change its behavior based on empty section blocks...  Seems like a more robust, less-surprising way for things to behave.

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
Could you throw in a couple unit tests that test the absolute-path cloning?

**Review by aeslaughter — COMMENTED** [review]
Can you add some unit testing?

**Comment by dschwen** [comment]
Added. This also adds the ability to run walkers on a node _after_ the children were traversed. I'm thinking there should be a virtual method on the Walker class to return the default NodeType the Walker should apply to and the default mode (children first/last). For some walkers only a specific combination of settings makes sense.

**Review by aeslaughter — APPROVED** [review]

**Pull request merged**
